#!/bin/bash

# Comandos individuais para restaurar cada tabela com pv (progresso)
# Execute um comando por vez copiando e colando no terminal

# Carregar DATABASE_URL_OFICIAL do .env
export DATABASE_URL_OFICIAL=$(grep -E "^DATABASE_URL_OFICIAL=" .env | cut -d= -f2- | sed 's/^"//;s/"$//')

echo "=== COMANDOS PARA RESTAURAR TABELAS COM PV ==="
echo ""
echo "1. tags:"
echo "psql -d \"\$DATABASE_URL_OFICIAL\" -c \"TRUNCATE TABLE public.tags CASCADE;\" && pv dumps/dumps_chunks/tags.sql | grep -v -E '^\\\\[^.]' | psql -d \"\$DATABASE_URL_OFICIAL\""
echo ""
echo "2. tag_aliases:"
echo "psql -d \"\$DATABASE_URL_OFICIAL\" -c \"TRUNCATE TABLE public.tag_aliases CASCADE;\" && pv dumps/dumps_chunks/tag_aliases.sql | grep -v -E '^\\\\[^.]' | psql -d \"\$DATABASE_URL_OFICIAL\""
echo ""
echo "3. form_schemas:"
echo "psql -d \"\$DATABASE_URL_OFICIAL\" -c \"TRUNCATE TABLE public.form_schemas CASCADE;\" && pv dumps/dumps_chunks/form_schemas.sql | grep -v -E '^\\\\[^.]' | psql -d \"\$DATABASE_URL_OFICIAL\""
echo ""
echo "4. form_questions:"
echo "psql -d \"\$DATABASE_URL_OFICIAL\" -c \"TRUNCATE TABLE public.form_questions CASCADE;\" && pv dumps/dumps_chunks/form_questions.sql | grep -v -E '^\\\\[^.]' | psql -d \"\$DATABASE_URL_OFICIAL\""
echo ""
echo "5. funnels:"
echo "psql -d \"\$DATABASE_URL_OFICIAL\" -c \"TRUNCATE TABLE public.funnels CASCADE;\" && pv dumps/dumps_chunks/funnels.sql | grep -v -E '^\\\\[^.]' | psql -d \"\$DATABASE_URL_OFICIAL\""
echo ""
echo "6. funnel_stages:"
echo "psql -d \"\$DATABASE_URL_OFICIAL\" -c \"TRUNCATE TABLE public.funnel_stages CASCADE;\" && pv dumps/dumps_chunks/funnel_stages.sql | grep -v -E '^\\\\[^.]' | psql -d \"\$DATABASE_URL_OFICIAL\""
echo ""
echo "7. funnel_aliases:"
echo "psql -d \"\$DATABASE_URL_OFICIAL\" -c \"TRUNCATE TABLE public.funnel_aliases CASCADE;\" && pv dumps/dumps_chunks/funnel_aliases.sql | grep -v -E '^\\\\[^.]' | psql -d \"\$DATABASE_URL_OFICIAL\""
echo ""
echo "8. funnel_stage_aliases:"
echo "psql -d \"\$DATABASE_URL_OFICIAL\" -c \"TRUNCATE TABLE public.funnel_stage_aliases CASCADE;\" && pv dumps/dumps_chunks/funnel_stage_aliases.sql | grep -v -E '^\\\\[^.]' | psql -d \"\$DATABASE_URL_OFICIAL\""
echo ""
echo "9. lead_stats:"
echo "psql -d \"\$DATABASE_URL_OFICIAL\" -c \"TRUNCATE TABLE public.lead_stats CASCADE;\" && pv dumps/dumps_chunks/lead_stats.sql | grep -v -E '^\\\\[^.]' | psql -d \"\$DATABASE_URL_OFICIAL\""
echo ""
echo "10. leads:"
echo "psql -d \"\$DATABASE_URL_OFICIAL\" -c \"TRUNCATE TABLE public.leads CASCADE;\" && pv dumps/dumps_chunks/leads.sql | grep -v -E '^\\\\[^.]' | psql -d \"\$DATABASE_URL_OFICIAL\""
echo ""
echo "11. lead_identifiers:"
echo "psql -d \"\$DATABASE_URL_OFICIAL\" -c \"TRUNCATE TABLE public.lead_identifiers CASCADE;\" && pv dumps/dumps_chunks/lead_identifiers.sql | grep -v -E '^\\\\[^.]' | psql -d \"\$DATABASE_URL_OFICIAL\""
echo ""
echo "12. lead_sources:"
echo "psql -d \"\$DATABASE_URL_OFICIAL\" -c \"TRUNCATE TABLE public.lead_sources CASCADE;\" && pv dumps/dumps_chunks/lead_sources.sql | grep -v -E '^\\\\[^.]' | psql -d \"\$DATABASE_URL_OFICIAL\""
echo ""
echo "13. lead_tags:"
echo "psql -d \"\$DATABASE_URL_OFICIAL\" -c \"TRUNCATE TABLE public.lead_tags CASCADE;\" && pv dumps/dumps_chunks/lead_tags.sql | grep -v -E '^\\\\[^.]' | psql -d \"\$DATABASE_URL_OFICIAL\""
echo ""
echo "14. lead_events:"
echo "psql -d \"\$DATABASE_URL_OFICIAL\" -c \"TRUNCATE TABLE public.lead_events CASCADE;\" && pv dumps/dumps_chunks/lead_events.sql | grep -v -E '^\\\\[^.]' | psql -d \"\$DATABASE_URL_OFICIAL\""
echo ""
echo "15. lead_funnel_entries:"
echo "psql -d \"\$DATABASE_URL_OFICIAL\" -c \"TRUNCATE TABLE public.lead_funnel_entries CASCADE;\" && pv dumps/dumps_chunks/lead_funnel_entries.sql | grep -v -E '^\\\\[^.]' | psql -d \"\$DATABASE_URL_OFICIAL\""
echo ""
echo "16. lead_funnel_transitions:"
echo "psql -d \"\$DATABASE_URL_OFICIAL\" -c \"TRUNCATE TABLE public.lead_funnel_transitions CASCADE;\" && pv dumps/dumps_chunks/lead_funnel_transitions.sql | grep -v -E '^\\\\[^.]' | psql -d \"\$DATABASE_URL_OFICIAL\""
echo ""
echo "17. form_submissions:"
echo "psql -d \"\$DATABASE_URL_OFICIAL\" -c \"TRUNCATE TABLE public.form_submissions CASCADE;\" && pv dumps/dumps_chunks/form_submissions.sql | grep -v -E '^\\\\[^.]' | psql -d \"\$DATABASE_URL_OFICIAL\""
echo ""
echo "18. form_answers:"
echo "psql -d \"\$DATABASE_URL_OFICIAL\" -c \"TRUNCATE TABLE public.form_answers CASCADE;\" && pv dumps/dumps_chunks/form_answers.sql | grep -v -E '^\\\\[^.]' | psql -d \"\$DATABASE_URL_OFICIAL\""
echo ""


